In [8]:
import pandas as pd
import plotly.express as px

car_data = pd.read_csv('../vehicles_us.csv') # lendo os dados
print(car_data.info())
display(car_data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103053 entries, 0 to 103052
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         103053 non-null  object
 1   model_year    95813 non-null   object
 2   model         103051 non-null  object
 3   condition     103051 non-null  object
 4   cylinders     92531 non-null   object
 5   fuel          103051 non-null  object
 6   odometer      87267 non-null   object
 7   transmission  103051 non-null  object
 8   type          103051 non-null  object
 9   paint_color   84517 non-null   object
 10  is_4wd        51145 non-null   object
 11  date_posted   103051 non-null  object
 12  days_listed   103051 non-null  object
dtypes: object(13)
memory usage: 10.2+ MB
None

C:\Users\aathi\AppData\Local\Temp\ipykernel_13568\1041477717.py:4: DtypeWarning:

Columns (1,4,6,10,12) have mixed types. Specify dtype option on import or set low_memory=False.

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [9]:
# Exemplo do projeto

fig = px.histogram(car_data, x="odometer") # criar um histograma
fig.show() # exibindo
print()
print()
fig = px.scatter(car_data, x="odometer", y="price") # criar um gráfico de dispersão
fig.show() # exibindo

In [10]:
# Remover carros sem preço definido
car_data_clean = car_data.dropna(subset=['price'])
carros_baratos = car_data_clean.sort_values('price').head(10)
display(carros_baratos)

for col in ["price", "odometer", "model_year", "days_listed"]:
        if col in car_data.columns:
            car_data[col] = pd.to_numeric(car_data[col], errors="coerce")

# Top 5 modelos mais baratos
top5_price = car_data.nsmallest(5, 'price')[['model', 'price']]
print(top5_price)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
19445,1,2003.0,chevrolet malibu,good,6,gas,190000.0,automatic,sedan,NaN,NaN,2018-11-20,51
68520,1,2015.0,gmc sierra 1500,excellent,10.0,gas,92945.0,other,truck,custom,1.0,2018-07-15,34.0
10886,1,2015.0,jeep grand cherokee,excellent,8,gas,42442.0,automatic,SUV,black,1.0,2019-03-30,16
16741,1,2016.0,toyota tundra,excellent,8,gas,23042.0,automatic,truck,black,1.0,2019-02-15,31
16742,1,2017.0,jeep wrangler,excellent,10,gas,38617.0,other,SUV,black,1.0,2018-10-01,75
10885,1,2014.0,ram 2500,excellent,6,gas,36830.0,automatic,truck,white,1.0,2018-05-13,35
10884,1,2014.0,toyota 4runner,excellent,6,gas,69153.0,automatic,SUV,blue,1.0,2018-10-27,32
48867,1,2014.0,jeep wrangler,excellent,10,gas,84902.0,other,SUV,custom,1.0,2019-04-12,15
16743,1,2012.0,jeep wrangler,excellent,6,gas,NaN,automatic,SUV,white,1.0,2018-10-11,26
16745,1,2015.0,ram 3500,excellent,6,gas,71719.0,automatic,truck,white,1.0,2018-10-15,46

                    model  price
405      chevrolet camaro    1.0
3063  chevrolet silverado    1.0
3808      chevrolet tahoe    1.0
3902           ford f-150    1.0
4140  chevrolet silverado    1.0

In [11]:
# Valores únicos em ordem crescente
precos_ordenados = sorted(car_data['price'].unique())
print(precos_ordenados)

[np.float64(1.0), np.float64(3.0), np.float64(5.0), np.float64(6.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(15.0), np.float64(20.0), np.float64(24.0), np.float64(25.0), np.float64(28.0), np.float64(32.0), np.float64(35.0), np.float64(36.0), np.float64(39.0), np.float64(65.0), np.float64(69.0), np.float64(80.0), np.float64(85.0), np.float64(105.0), np.float64(111.0), np.float64(147.0), np.float64(155.0), np.float64(169.0), np.float64(171.0), np.float64(176.0), np.float64(179.0), np.float64(180.0), np.float64(185.0), np.float64(187.0), np.float64(188.0), np.float64(190.0), np.float64(195.0), np.float64(196.0), np.float64(197.0), np.float64(198.0), np.float64(199.0), np.float64(200.0), np.float64(204.0), np.float64(206.0), np.float64(211.0), np.float64(215.0), np.float64(222.0), np.float64(228.0), np.float64(233.0), np.float64(237.0), np.float64(243.0), np.float64(244.0), np.float64(245.0), np.float64(246.0), np.float64(247.0), np.float64(250.0), np.float64(253.0), np.float64(255.0), np.float64(257.0), np.float64(267.0), np.float64(276.0), np.float64(277.0), np.float64(279.0), np.float64(287.0), np.float64(288.0), np.float64(289.0), np.float64(292.0), np.float64(295.0), np.float64(298.0), np.float64(299.0), np.float64(300.0), np.float64(313.0), np.float64(320.0), np.float64(326.0), np.float64(340.0), np.float64(350.0), np.float64(351.0), np.float64(359.0), np.float64(371.0), np.float64(372.0), np.float64(384.0), np.float64(388.0), np.float64(399.0), np.float64(400.0), np.float64(422.0), np.float64(439.0), np.float64(450.0), np.float64(460.0), np.float64(472.0), np.float64(475.0), np.float64(483.0), np.float64(495.0), np.float64(500.0), np.float64(534.0), np.float64(550.0), np.float64(575.0), np.float64(580.0), np.float64(590.0), np.float64(599.0), np.float64(600.0), np.float64(650.0), np.float64(695.0), np.float64(699.0), np.float64(700.0), np.float64(725.0), np.float64(750.0), np.float64(795.0), np.float64(800.0), np.float64(850.0), np.float64(855.0), np.float64(875.0), np.float64(895.0), np.float64(899.0), np.float64(900.0), np.float64(950.0), np.float64(975.0), np.float64(995.0), np.float64(999.0), np.float64(1000.0), np.float64(1005.0), np.float64(1050.0), np.float64(1095.0), np.float64(1099.0), np.float64(1100.0), np.float64(1111.0), np.float64(1150.0), np.float64(1188.0), np.float64(1190.0), np.float64(1195.0), np.float64(1200.0), np.float64(1234.0), np.float64(1250.0), np.float64(1275.0), np.float64(1290.0), np.float64(1295.0), np.float64(1299.0), np.float64(1300.0), np.float64(1350.0), np.float64(1395.0), np.float64(1400.0), np.float64(1432.0), np.float64(1450.0), np.float64(1475.0), np.float64(1477.0), np.float64(1478.0), np.float64(1488.0), np.float64(1490.0), np.float64(1495.0), np.float64(1499.0), np.float64(1500.0), np.float64(1550.0), np.float64(1575.0), np.float64(1595.0), np.float64(1599.0), np.float64(1600.0), np.float64(1650.0), np.float64(1675.0), np.float64(1680.0), np.float64(1695.0), np.float64(1698.0), np.float64(1700.0), np.float64(1750.0), np.float64(1795.0), np.float64(1798.0), np.float64(1799.0), np.float64(1800.0), np.float64(1850.0), np.float64(1865.0), np.float64(1873.0), np.float64(1875.0), np.float64(1877.0), np.float64(1895.0), np.float64(1896.0), np.float64(1897.0), np.float64(1899.0), np.float64(1900.0), np.float64(1925.0), np.float64(1950.0), np.float64(1975.0), np.float64(1980.0), np.float64(1988.0), np.float64(1990.0), np.float64(1995.0), np.float64(1997.0), np.float64(1998.0), np.float64(1999.0), np.float64(2000.0), np.float64(2025.0), np.float64(2075.0), np.float64(2095.0), np.float64(2100.0), np.float64(2150.0), np.float64(2175.0), np.float64(2195.0), np.float64(2199.0), np.float64(2200.0), np.float64(2220.0), np.float64(2250.0), np.float64(2275.0), np.float64(2295.0), np.float64(2298.0), np.float64(2299.0), np.float64(2300.0), np.float64(2348.0), np.float64(2350.0), np.float64(2374.0), np.float64(2375.0), np.float64(2385.0), np.float64(2390.0), np.float64(2395.0), np.float64(2399.0), np.float64(2400.0), np.float64(2450.0), np.float64(2475.0), np.float64(2483.0), np.float64(2485.0), np.float64(2488.0), np.float64(2490.0), np.float64(2493.0), np.float64(2495.0), np.float64(2497.0), np.float64(2498.0), np.float64(2499.0), np.float64(2500.0), np.float64(2550.0), np.float64(2559.0), np.float64(2575.0), np.float64(2583.0), np.float64(2585.0), np.float64(2588.0), np.float64(2595.0), np.float64(2599.0), np.float64(2600.0), np.float64(2650.0), np.float64(2670.0), np.float64(2675.0), np.float64(2690.0), np.float64(2695.0), np.float64(2699.0), np.float64(2700.0), np.float64(2735.0), np.float64(2739.0), np.float64(2741.0), np.float64(2749.0), np.float64(2750.0), np.float64(2775.0), np.float64(2788.0), np.float64(2789.0), np.float64(2790.0), np.float64(2795.0), np.float64(2798.0), np.float64(2799.0), np.float64(2800.0), np.float64(2850.0), np.float64(2870.0), np.float64(2887.0), np.float64(2890.0), np.float64(2895.0), np.float64(2897.0), np.float64(2899.0), np.float64(2900.0), np.float64(2945.0), np.float64(2950.0), np.float64(2959.0), np.float64(2975.0), np.float64(2977.0), np.float64(2980.0), np.float64(2988.0), np.float64(2990.0), np.float64(2992.0), np.float64(2994.0), np.float64(2995.0), np.float64(2997.0), np.float64(2998.0), np.float64(2999.0), np.float64(3000.0), np.float64(3050.0), np.float64(3058.0), np.float64(3095.0), np.float64(3100.0), np.float64(3138.0), np.float64(3150.0), np.float64(3170.0), np.float64(3175.0), np.float64(3195.0), np.float64(3199.0), np.float64(3200.0), np.float64(3230.0), np.float64(3249.0), np.float64(3250.0), np.float64(3255.0), np.float64(3275.0), np.float64(3290.0), np.float64(3295.0), np.float64(3296.0), np.float64(3299.0), np.float64(3300.0), np.float64(3333.0), np.float64(3350.0), np.float64(3375.0), np.float64(3387.0), np.float64(3395.0), np.float64(3397.0), np.float64(3400.0), np.float64(3412.0), np.float64(3425.0), np.float64(3440.0), np.float64(3450.0), np.float64(3459.0), np.float64(3475.0), np.float64(3480.0), np.float64(3485.0), np.float64(3488.0), np.float64(3490.0), np.float64(3493.0), np.float64(3495.0), np.float64(3497.0), np.float64(3498.0), np.float64(3499.0), np.float64(3500.0), np.float64(3525.0), np.float64(3550.0), np.float64(3575.0), np.float64(3586.0), np.float64(3588.0), np.float64(3590.0), np.float64(3591.0), np.float64(3595.0), np.float64(3599.0), np.float64(3600.0), np.float64(3636.0), np.float64(3640.0), np.float64(3650.0), np.float64(3670.0), np.float64(3675.0), np.float64(3690.0), np.float64(3695.0), np.float64(3698.0), np.float64(3699.0), np.float64(3700.0), np.float64(3715.0), np.float64(3725.0), np.float64(3744.0), np.float64(3748.0), np.float64(3749.0), np.float64(3750.0), np.float64(3765.0), np.float64(3769.0), np.float64(3775.0), np.float64(3777.0), np.float64(3790.0), np.float64(3793.0), np.float64(3795.0), np.float64(3796.0), np.float64(3799.0), np.float64(3800.0), np.float64(3845.0), np.float64(3850.0), np.float64(3860.0), np.float64(3874.0), np.float64(3879.0), np.float64(3888.0), np.float64(3890.0), np.float64(3895.0), np.float64(3896.0), np.float64(3899.0), np.float64(3900.0), np.float64(3901.0), np.float64(3919.0), np.float64(3920.0), np.float64(3945.0), np.float64(3950.0), np.float64(3955.0), np.float64(3973.0), np.float64(3975.0), np.float64(3977.0), np.float64(3979.0), np.float64(3980.0), np.float64(3985.0), np.float64(3988.0), np.float64(3990.0), np.float64(3991.0), np.float64(3992.0), np.float64(3993.0), np.float64(3995.0), np.float64(3996.0), np.float64(3997.0), np.float64(3998.0), np.float64(3999.0), np.float64(4000.0), np.float64(4025.0), np.float64(4100.0), np.float64(4150.0), np.float64(4170.0), np.float64(4195.0), np.float64(4197.0), np.float64(4199.0), np.float64(4200.0), np.float64(4249.0), np.float64(4250.0), np.float64(4262.0), np.float64(4275.0), np.float64(4290.0), np.float64(4295.0), np.float64(4299.0), np.float64(4300.0), np.float64(4345.0), np.float64(4347.0), np.float64(4350.0), np.float64(4388.0), np.float64(4390.0), np.float64(4395.0), np.float64(4399.0), np.float64(4400.0), np.float64(4411.0), np.float64(4425.0), np.float64(4450.0), np.float64(4475.0), np.float64(4477.0), np.float64(4484.0), np.float64(4488.0), np.float64(4490.0), np.float64(4492.0), np.float64(4495.0), np.float64(4497.0), np.float64(4498.0), np.float64(4499.0), np.float64(4500.0), np.float64(4550.0), np.float64(4555.0), np.float64(4560.0), np.float64(4575.0), np.float64(4590.0), np.float64(4595.0), np.float64(4596.0), np.float64(4598.0), np.float64(4599.0), np.float64(4600.0), np.float64(4620.0), np.float64(4650.0), np.float64(4670.0), np.float64(4675.0), np.float64(4678.0), np.float64(4690.0), np.float64(4695.0), np.float64(4699.0), np.float64(4700.0), np.float64(4701.0), np.float64(4720.0), np.float64(4725.0), np.float64(4750.0), np.float64(4775.0), np.float64(4777.0), np.float64(4780.0), np.float64(4785.0), np.float64(4788.0), np.float64(4789.0), np.float64(4790.0), np.float64(4795.0), np.float64(4799.0), np.float64(4800.0), np.float64(4825.0), np.float64(4826.0), np.float64(4830.0), np.float64(4850.0), np.float64(4855.0), np.float64(4875.0), np.float64(4877.0), np.float64(4890.0), np.float64(4895.0), np.float64(4899.0), np.float64(4900.0), np.float64(4901.0), np.float64(4910.0), np.float64(4915.0), np.float64(4950.0), np.float64(4953.0), np.float64(4959.0), np.float64(4962.0), np.float64(4965.0), np.float64(4970.0), np.float64(4975.0), np.float64(4977.0), np.float64(4980.0), np.float64(4985.0), np.float64(4987.0), np.float64(4988.0), np.float64(4989.0), np.float64(4990.0), np.float64(4991.0), np.float64(4992.0), np.float64(4994.0), np.float64(4995.0), np.float64(4996.0), np.float64(4997.0), np.float64(4998.0), np.float64(4999.0), np.float64(5000.0), np.float64(5065.0), np.float64(5099.0), np.float64(5100.0), np.float64(5125.0), np.float64(5150.0), np.float64(5170.0), np.float64(5195.0), np.float64(5199.0), np.float64(5200.0), np.float64(5236.0), np.float64(5249.0), np.float64(5250.0), np.float64(5255.0), np.float64(5265.0), np.float64(5275.0), np.float64(5289.0), np.float64(5290.0), np.float64(5295.0), np.float64(5298.0), np.float64(5299.0), np.float64(5300.0), np.float64(5303.0), np.float64(5322.0), np.float64(5350.0), np.float64(5364.0), np.float64(5374.0), np.float64(5375.0), np.float64(5387.0), np.float64(5390.0), np.float64(5395.0), np.float64(5397.0), np.float64(5399.0), np.float64(5400.0), np.float64(5430.0), np.float64(5440.0), np.float64(5445.0), np.float64(5450.0), np.float64(5476.0), np.float64(5477.0), np.float64(5480.0), np.float64(5488.0), np.float64(5490.0), np.float64(5493.0), np.float64(5495.0), np.float64(5497.0), np.float64(5498.0), np.float64(5499.0), np.float64(5500.0), np.float64(5550.0), np.float64(5555.0), np.float64(5573.0), np.float64(5582.0), np.float64(5588.0), np.float64(5590.0), np.float64(5595.0), np.float64(5599.0), np.float64(5600.0), np.float64(5650.0), np.float64(5670.0), np.float64(5675.0), np.float64(5680.0), np.float64(5690.0), np.float64(5695.0), np.float64(5696.0), np.float64(5697.0), np.float64(5698.0), np.float64(5699.0), np.float64(5700.0), np.float64(5707.0), np.float64(5717.0), np.float64(5725.0), np.float64(5728.0), np.float64(5733.0), np.float64(5736.0), np.float64(5745.0), np.float64(5750.0), np.float64(5755.0), np.float64(5758.0), np.float64(5770.0), np.float64(5775.0), np.float64(5777.0), np.float64(5785.0), np.float64(5788.0), np.float64(5789.0), np.float64(5790.0), np.float64(5795.0), np.float64(5799.0), np.float64(5800.0), np.float64(5825.0), np.float64(5840.0), np.float64(5850.0), np.float64(5869.0), np.float64(5875.0), np.float64(5877.0), np.float64(5888.0), np.float64(5890.0), np.float64(5892.0), np.float64(5895.0), np.float64(5899.0), np.float64(5900.0), np.float64(5901.0), np.float64(5905.0), np.float64(5909.0), np.float64(5910.0), np.float64(5928.0), np.float64(5949.0), np.float64(5950.0), np.float64(5963.0), np.float64(5970.0), np.float64(5973.0), np.float64(5975.0), np.float64(5977.0), np.float64(5980.0), np.float64(5984.0), np.float64(5985.0), np.float64(5987.0), np.float64(5988.0), np.float64(5990.0), np.float64(5991.0), np.float64(5992.0), np.float64(5993.0), np.float64(5995.0), np.float64(5997.0), np.float64(5998.0), np.float64(5999.0), np.float64(6000.0), np.float64(6025.0), np.float64(6050.0), np.float64(6095.0), np.float64(6100.0), np.float64(6145.0), np.float64(6150.0), np.float64(6170.0), np.float64(6183.0), np.float64(6194.0), np.float64(6195.0), np.float64(6197.0), np.float64(6199.0), np.float64(6200.0), np.float64(6245.0), np.float64(6249.0), np.float64(6250.0), np.float64(6279.0), np.float64(6285.0), np.float64(6290.0), np.float64(6295.0), np.float64(6297.0), np.float64(6299.0), np.float64(6300.0), np.float64(6311.0), np.float64(6332.0), np.float64(6348.0), np.float64(6350.0), np.float64(6353.0), np.float64(6355.0), np.float64(6390.0), np.float64(6395.0), np.float64(6399.0), np.float64(6400.0), np.float64(6420.0), np.float64(6424.0), np.float64(6425.0), np.float64(6440.0), np.float64(6443.0), np.float64(6445.0), np.float64(6450.0), np.float64(6451.0), np.float64(6455.0), np.float64(6465.0), np.float64(6475.0), np.float64(6477.0), np.float64(6480.0), np.float64(6490.0), np.float64(6495.0), np.float64(6498.0), np.float64(6499.0), np.float64(6500.0), np.float64(6509.0), np.float64(6520.0), np.float64(6535.0), np.float64(6540.0), np.float64(6550.0), np.float64(6552.0), np.float64(6555.0), np.float64(6570.0), np.float64(6573.0), np.float64(6575.0), np.float64(6580.0), np.float64(6588.0), np.float64(6590.0), np.float64(6592.0), np.float64(6595.0), np.float64(6596.0), np.float64(6598.0), np.float64(6599.0), np.float64(6600.0), np.float64(6650.0), np.float64(6665.0), np.float64(6675.0), np.float64(6680.0), np.float64(6690.0), np.float64(6695.0), np.float64(6699.0), np.float64(6700.0), np.float64(6749.0), np.float64(6750.0), np.float64(6757.0), np.float64(6775.0), np.float64(6777.0), np.float64(6785.0), np.float64(6789.0), np.float64(6790.0), np.float64(6795.0), np.float64(6798.0), np.float64(6799.0), np.float64(6800.0), np.float64(6845.0), np.float64(6850.0), np.float64(6858.0), np.float64(6870.0), np.float64(6877.0), np.float64(6880.0), np.float64(6885.0), np.float64(6888.0), np.float64(6890.0), np.float64(6895.0), np.float64(6899.0), np.float64(6900.0), np.float64(6901.0), np.float64(6906.0), np.float64(6921.0), np.float64(6932.0), np.float64(6934.0), np.float64(6948.0), np.float64(6950.0), np.float64(6961.0), np.float64(6962.0), np.float64(6964.0), np.float64(6972.0), np.float64(6975.0), np.float64(6977.0), np.float64(6980.0), np.float64(6985.0), np.float64(6988.0), np.float64(6990.0), np.float64(6991.0), np.float64(6992.0), np.float64(6994.0), np.float64(6995.0), np.float64(6996.0), np.float64(6997.0), np.float64(6998.0), np.float64(6999.0), np.float64(7000.0), np.float64(7100.0), np.float64(7143.0), np.float64(7150.0), np.float64(7190.0), np.float64(7194.0), np.float64(7195.0), np.float64(7199.0), np.float64(7200.0), np.float64(7205.0), np.float64(7234.0), np.float64(7245.0), np.float64(7249.0), np.float64(7250.0), np.float64(7277.0), np.float64(7289.0), np.float64(7290.0), np.float64(7295.0), np.float64(7299.0), np.float64(7300.0), np.float64(7349.0), np.float64(7350.0), np.float64(7356.0), np.float64(7373.0), np.float64(7377.0), np.float64(7380.0), np.float64(7388.0), np.float64(7395.0), np.float64(7398.0), np.float64(7399.0), np.float64(7400.0), np.float64(7449.0), np.float64(7450.0), np.float64(7455.0), np.float64(7470.0), np.float64(7474.0), np.float64(7475.0), np.float64(7477.0), np.float64(7486.0), np.float64(7487.0), np.float64(7488.0), np.float64(7490.0), np.float64(7492.0), np.float64(7495.0), np.float64(7497.0), np.float64(7498.0), np.float64(7499.0), np.float64(7500.0), np.float64(7535.0), np.float64(7550.0), np.float64(7566.0), np.float64(7577.0), np.float64(7585.0), np.float64(7590.0), np.float64(7595.0), np.float64(7597.0), np.float64(7599.0), np.float64(7600.0), np.float64(7650.0), np.float64(7666.0), np.float64(7670.0), np.float64(7677.0), np.float64(7688.0), np.float64(7690.0), np.float64(7694.0), np.float64(7695.0), np.float64(7698.0), np.float64(7699.0), np.float64(7700.0), np.float64(7725.0), np.float64(7745.0), np.float64(7749.0), np.float64(7750.0), np.float64(7757.0), np.float64(7763.0), np.float64(7775.0), np.float64(7777.0), np.float64(7785.0), np.float64(7789.0), np.float64(7795.0), np.float64(7799.0), np.float64(7800.0), np.float64(7829.0), np.float64(7833.0), np.float64(7847.0), np.float64(7850.0), np.float64(7860.0), np.float64(7875.0), np.float64(7877.0), np.float64(7887.0), np.float64(7888.0), np.float64(7890.0), np.float64(7894.0), np.float64(7895.0), np.float64(7896.0), np.float64(7898.0), np.float64(7899.0), np.float64(7900.0), np.float64(7905.0), np.float64(7910.0), np.float64(7913.0), np.float64(7914.0), np.float64(7915.0), np.float64(7918.0), np.float64(7926.0), np.float64(7945.0), np.float64(7950.0), np.float64(7973.0), np.float64(7974.0), np.float64(7975.0), np.float64(7976.0), np.float64(7979.0), np.float64(7980.0), np.float64(7985.0), np.float64(7988.0), np.float64(7989.0), np.float64(7990.0), np.float64(7991.0), np.float64(7992.0), np.float64(7994.0), np.float64(7995.0), np.float64(7997.0), np.float64(7998.0), np.float64(7999.0), np.float64(8000.0), np.float64(8001.0), np.float64(8025.0), np.float64(8081.0), np.float64(8085.0), np.float64(8095.0), np.float64(8099.0), np.float64(8100.0), np.float64(8111.0), np.float64(8128.0), np.float64(8133.0), np.float64(8150.0), np.float64(8171.0), np.float64(8176.0), np.float64(8177.0), np.float64(8181.0), np.float64(8194.0), np.float64(8195.0), np.float64(8199.0), np.float64(8200.0), np.float64(8225.0), np.float64(8250.0), np.float64(8266.0), np.float64(8273.0), np.float64(8275.0), np.float64(8282.0), np.float64(8288.0), np.float64(8290.0), np.float64(8295.0), np.float64(8297.0), np.float64(8299.0), np.float64(8300.0), np.float64(8305.0), np.float64(8343.0), np.float64(8345.0), np.float64(8346.0), np.float64(8349.0), np.float64(8350.0), np.float64(8360.0), np.float64(8380.0), np.float64(8390.0), np.float64(8394.0), np.float64(8395.0), np.float64(8399.0), np.float64(8400.0), np.float64(8401.0), np.float64(8420.0), np.float64(8425.0), np.float64(8445.0), np.float64(8447.0), np.float64(8448.0), np.float64(8450.0), np.float64(8455.0), np.float64(8459.0), np.float64(8470.0), np.float64(8475.0), np.float64(8477.0), np.float64(8480.0), np.float64(8488.0), np.float64(8490.0), np.float64(8494.0), np.float64(8495.0), np.float64(8497.0), np.float64(8498.0), np.float64(8499.0), np.float64(8500.0), np.float64(8550.0), np.float64(8575.0), np.float64(8588.0), np.float64(8590.0), np.float64(8595.0), np.float64(8596.0), np.float64(8597.0), np.float64(8599.0), np.float64(8600.0), np.float64(8611.0), np.float64(8625.0), np.float64(8650.0), np.float64(8675.0), np.float64(8677.0), np.float64(8678.0), np.float64(8680.0), np.float64(8683.0), np.float64(8685.0), np.float64(8688.0), np.float64(8690.0), np.float64(8695.0), np.float64(8698.0), np.float64(8699.0), np.float64(8700.0), np.float64(8701.0), np.float64(8722.0), np.float64(8725.0), np.float64(8749.0), np.float64(8750.0), np.float64(8773.0), np.float64(8775.0), np.float64(8777.0), np.float64(8782.0), np.float64(8785.0), np.float64(8788.0), np.float64(8789.0), np.float64(8795.0), np.float64(8797.0), np.float64(8798.0), np.float64(8799.0), np.float64(8800.0), np.float64(8802.0), np.float64(8845.0), np.float64(8849.0), np.float64(8850.0), np.float64(8869.0), np.float64(8871.0), np.float64(8875.0), np.float64(8876.0), np.float64(8877.0), np.float64(8880.0), np.float64(8887.0), np.float64(8888.0), np.float64(8890.0), np.float64(8895.0), np.float64(8899.0), np.float64(8900.0), np.float64(8902.0), np.float64(8905.0), np.float64(8913.0), np.float64(8915.0), np.float64(8925.0), np.float64(8945.0), np.float64(8950.0), np.float64(8951.0), np.float64(8967.0), np.float64(8970.0), np.float64(8975.0), n

In [12]:
# Quantos preços diferentes existem
quantidade_precos = car_data['price'].nunique()
print(f"Existem {quantidade_precos} preços únicos")

Existem 3443 preços únicos

In [13]:
# Os 10 preços que mais aparecem
precos_comuns = car_data['price'].value_counts().head(10)
print(precos_comuns)

price
1.0       1596
6995.0    1438
5995.0    1310
4995.0    1248
3500.0    1240
7995.0    1232
5500.0    1230
4500.0    1216
8995.0    1098
6500.0    1056
Name: count, dtype: int64

In [14]:
min_price = 1000  # ajuste de preço mínimo
common_prices_filtered = [p for p in precos_comuns.index if p is not None and p >= min_price]
cols = ['price','model_year','model','condition','odometer','transmission','type','paint_color']
dfp = car_data[car_data['price'].isin(common_prices_filtered)].copy()
dfp['odometer'] = pd.to_numeric(dfp['odometer'], errors='coerce')

# (opcional) evitar repetição do mesmo modelo no mesmo preço
dfp = dfp.sort_values(['price','model','odometer']).drop_duplicates(['price','model'], keep='first')

top3_per_price = (
    dfp
    .sort_values(['price','odometer','model_year'], ascending=[True,True,False])
    .groupby('price', group_keys=False)
    .head(3)[cols]
)

print(top3_per_price)

        price  model_year                model  condition  odometer  \
35482  3500.0      2008.0           ford focus  excellent     126.0
46913  3500.0         NaN       subaru outback       good     153.0
13605  3500.0      2004.0  jeep grand cherokee       good     154.0
23025  4500.0      1970.0           ford f-250       good       0.0
18405  4500.0      2010.0       toyota corolla  excellent       1.0
45243  4500.0      2004.0         toyota camry  excellent     100.0
34671  4995.0      2010.0     chevrolet malibu       good     152.0
929    4995.0      2003.0           ford f-150   like new     181.0
15227  4995.0      1998.0     chevrolet camaro       good   28170.0
27631  5500.0      2008.0        toyota sienna       good     145.0
25490  5500.0         NaN        nissan altima  excellent     170.0
20714  5500.0      2005.0      nissan frontier  excellent     200.0
11793  5995.0      2005.0            gmc yukon       good       0.0
18620  5995.0      2002.0             ram 2500       good       0.0
1919   5995.0      2012.0        ford focus se  excellent      67.0
7538   6500.0      2013.0        nissan sentra  excellent      63.0
35534  6500.0      2014.0      hyundai elantra  excellent      71.0
43525  6500.0         NaN         honda accord  excellent     103.0
12292  6995.0      2013.0  dodge grand caravan  excellent      99.0
9864   6995.0      2013.0     chevrolet malibu       good     100.0
24763  6995.0      2010.0         toyota prius  excellent     114.0
36746  7995.0      2015.0      chevrolet cruze  excellent     111.0
36749  7995.0      1999.0        jeep wrangler       good     176.0
36772  7995.0      2007.0          toyota rav4       good     184.0
1337   8995.0      2008.0      chevrolet tahoe  excellent     240.0
50750  8995.0      2018.0         nissan versa   like new   11580.0
30442  8995.0      2017.0      hyundai elantra  excellent   21558.0

      transmission         type paint_color
35482    automatic        sedan         NaN
46913       manual        wagon        blue
13605    automatic          SUV       black
23025    automatic       pickup       white
18405    automatic        sedan      silver
45243    automatic        sedan      silver
34671    automatic        sedan         red
929      automatic        truck       brown
15227    automatic  convertible         red
27631    automatic     mini-van        grey
25490    automatic        sedan       white
20714    automatic          SUV       white
11793        other          SUV      custom
18620    automatic        truck         NaN
1919     automatic    hatchback      silver
7538     automatic        sedan      silver
35534    automatic        sedan         red
43525    automatic        coupe         red
12292    automatic     mini-van         red
9864        manual        sedan         NaN
24763    automatic    hatchback        grey
36746    automatic        sedan       white
36749       manual          SUV       green
36772    automatic          SUV         NaN
1337     automatic          SUV         NaN
50750       manual        sedan       black
30442    automatic        sedan        blue

In [16]:
print(car_data["is_4wd"].unique())
print(car_data["is_4wd"].dtype)

['1.0' nan 'is_4wd' 1.0]
object